name: Python Tests

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Validate formatting
        run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]
        tox_env:
          - py312-dj51-wt63
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -e ${{ matrix.tox_env }} -- index-url=https://pypi.python.org/simple/
      - name: Combine and report coverage
        run: tox -e coverage-report
      - name: Prepare artifacts
        run: |
          rm -rf coverage-artifacts  # Ensure the folder does not already exist
          mkdir coverage-artifacts
          find . -maxdepth 1 -name ".coverage*" -not -name "coverage-artifacts" -exec mv {} coverage-artifacts/ \;
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: coverage-artifacts/

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: coverage-data
          path: .
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Prepare Coverage Report
        run: |
          rm -rf coverage-final  # Ensure the folder does not already exist
          mkdir coverage-final
          find . -maxdepth 1 -name ".coverage*" -not -name "coverage-final" -exec mv {} coverage-final/ \;
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-final
          path: coverage-final/
